user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
worker_connections 768;
}

http {
  server {
    listen 443 ssl;
    server_name saturn;
    ssl_certificate        /etc/nginx/tls/nginx.crt;
    ssl_certificate_key    /etc/nginx/tls/nginx.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
      
    location / {
      root /etc/nginx/www;
    }
  }
}
